### ISSUE TITLE
Fix 7.30

### ISSUE THREAD

**Issue by 010Warrior** [simplyblk/Fortnitebuilds#16]
fix it and yes i extracted it fully installed it like 4 times and extracted it smh it crashes either way ive tried using launch.bat yk with arguments but crash so its probally a corrupted build if u can upload a new one that would be great ngl

![image](https://github.com/simplyblk/Fortnitebuilds/assets/110310521/7eb26a07-c5a5-41d2-b1d4-609e3f354e13)

**Comment by max8447** [comment]
yeah, pakchunk0_s5-WindowsClient.sig wasnt found (corrupted build)

**Comment by MrMeowzz** [comment]
heres a working download: https://drive.google.com/file/d/13pFfgfSttmrsySybWGr5hSFXORn5cdd2/view
