### ISSUE TITLE
12.41 not downloading

### ISSUE THREAD

**Issue by ajthegoa** [simplyblk/Fortnitebuilds#20]

**Comment by ryanmcd0nald** [comment]
12.41 download link leads page saying you are not authorized to view this object

**Comment by Daniel09876543210** [comment]
Use this google drive link for now, https://drive.google.com/file/d/1VdkncjSzL-81IUFIlVpQ39i11yip28qb/view

**Comment by simplyblk** [comment]
fixed, pipe down...
