### ISSUE TITLE
nice 12.41

### ISSUE THREAD

**Issue by CoolNiteYT** [simplyblk/Fortnitebuilds#21]
![image](https://github.com/simplyblk/Fortnitebuilds/assets/73061121/6469bf82-1bd1-4e80-81f7-f184870587f8)

**Comment by Daniel09876543210** [comment]
Use this google drive link, https://drive.google.com/file/d/1VdkncjSzL-81IUFIlVpQ39i11yip28qb/view

**Comment by simplyblk** [comment]
fixed, pipe down...
