### ISSUE TITLE
Website downloads points to wrong path

### ISSUE THREAD

**Issue by Zordon1337** [simplyblk/Fortnitebuilds#24]
^
for example 1.11 is pointing to https://cdn.simplyblk.com/1.11.rar but it's actually https://cdn.simplyblk.com/1.11.zip
probably there is other builds also pointing to wrong url

**Comment by simplyblk** [comment]
are you sure? I just checked 1.11, looks fine to me.

**Comment by Zordon1337** [comment]
> are you sure? I just checked 1.11, looks fine to me.

![image](https://github.com/simplyblk/Fortnitebuilds/assets/65111609/57e9838d-cfa5-4aea-93b4-53d737d0078a)

**Comment by simplyblk** [comment]
![image](https://github.com/simplyblk/Fortnitebuilds/assets/59186634/8956faca-aa97-419b-a318-cacf7cd91eab)

**Comment by Zordon1337** [comment]
> ![image](https://user-images.githubusercontent.com/59186634/264703583-8956faca-aa97-419b-a318-cacf7cd91eab.png)

i'm talking about the website, on website it redirects you to "1.11.rar" but it should redirect to "1.11.zip"

**Comment by simplyblk** [comment]
yea ur trolling
