### ISSUE TITLE
how to run the game?

### ISSUE THREAD

**Issue by grandpa1946** [simplyblk/Fortnitebuilds#29]
i'm just left with a login screen after running the game.

**Comment by max8447** [comment]
Thats an issue on your end, not the builds fault

**Comment by grandpa1946** [comment]
i'm just using the launcher.bat 
is this the wrong way?

**Comment by katopiler** [comment]
yeah, you need a launcher that launches the game and injects a DLL to redirect servers.

**Comment by tbone2k-git** [comment]
> yeah, you need a launcher that launches the game and injects a DLL to redirect servers. (thats the simpelist way)

Where do I get such a launcher? And do these old builds work with current servers? Probably not, so are there community based servers, can I run my own server for the old Fortnite builds and have some LAN gaming maybe?

Thank you! o)
