### ISSUE TITLE
Is their an archived version of 13.xx builds that are not the pre relese build that is on here.

### ISSUE THREAD

**Issue by gitdrug** [simplyblk/Fortnitebuilds#30]
Is there like 13.10 or 13.20? or are they lost forever?

**Comment by katopiler** [comment]
There is 13.40 on Era CDN. you can get it by using the era launcher

**Comment by DHyperYT** [comment]
> There is 13.40 on Era CDN. you can get it by using the era launcher

They have their own .exe in their builds and they redirect to their own servers

**Comment by max8447** [comment]
bro 13.40 is on easyinstaller get it from there
