### ISSUE TITLE
Downloads are stuck on 0b/s or something like that.

### ISSUE THREAD

**Issue by Nogget2244** [simplyblk/Fortnitebuilds#31]
The links work sure... But the downloads are just not moving. They are stuck on 0b/s. I even tried to download it on my phone but no luck :/  PLS HELP

**Comment by katopiler** [comment]
same for me.

**Comment by killswitch9838** [comment]
same

**Comment by TimmieDevelops** [comment]
same!

**Comment by PuedoYT** [comment]
same

**Comment by max8447** [comment]
Bro cloudflare blocked the downloads stfu

**Comment by Nogget2244** [comment]
Now it works

**Comment by mohmanpro** [comment]
how
