### ISSUE TITLE
fix dll

### ISSUE THREAD

**Issue by milonekaaa** [simplyblk/Fortnitebuilds#35]
howww to fix dll

**Comment by VerzeHxD** [comment]
what are you talking about

**Comment by YTEric10** [comment]
“cobalt.dll dll is not a valid dll, fix it in the settings tab” How to fix?

**Comment by YTEric10** [comment]
https://cdn.discordapp.com/attachments/1195281298084859964/1195281343437881344/VC_redist.arm64.exe?ex=65b36b7f&is=65a0f67f&hm=af5b09911f09e3a10370cb565873140bf301c4e82be6744a50efc745232c42fd&

**Comment by simplyblk** [comment]
Not the proper place to put this.
