### ISSUE TITLE
no 2.3?

### ISSUE THREAD

**Issue by CoolNiteYT** [simplyblk/Fortnitebuilds#7]
https://mega.nz/file/dfRHDbiQ#U_dg2YSoRsTgJpqSrejw2gpp6oJmle0An0lodDJZaZ0

im 99.999999999999% sure that this is 2.3

**Comment by max8447** [comment]
How r u not sure

**Comment by CoolNiteYT** [comment]
> How r u not sure

good (bad) question...

**Comment by simplyblk** [comment]
added
